# Generated by Django 5.2.9 on 2025-12-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disease_predict', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_comment', models.TextField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('reviewed', 'Reviewed')], default='none', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('disease_predict', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_requests', to='accounts.doctorprofile')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imageupload')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
